### PR TITLE
Fix reload-on-touch/change

### LINKED ISSUE #2681: 20.0.27 attach-daemon not responding to touching .ini file
<= 20.0.26 we've never had an issue with a couple of attach-daemon entries in our .ini files.
Now with 20.0.27 touching the file doesn't restart the daemons. We've changed nothing.

**UPDATE: Confirmed, touching an ini that used to restart python app and attach-daemon's no longer works on .27. We downgraded to .26 no problems at all.**

Of course, restarting uWSGI works just fine.

### PR DESCRIPTION
**Pull request by Lalufu**
As part of a fix for #2656, commit 8f1d0e5 introduced a measure to wait for processes to finish work while reloading. The code to do this affects other logic flows was well, breaking the ability to reload uwsgi when a config file changes.

This moves the code around a bit so #2656 stays fixed, but reload-on-touch/change works again.

Fixes #2681.

### CODE REVIEW

File: core/uwsgi.c [hunk 1]
```diff
@@ -1356,6 +1356,8 @@ void kill_them_all(int signum) {
 // gracefully destroy
 void gracefully_kill_them_all(int signum) {
 
+	    int waitpid_status;
```
Comment (xrmx) [inline core/uwsgi.c:1359]:
```suggestion
        int waitpid_status;
```

File: core/uwsgi.c [hunk 2]
```diff
@@ -1377,6 +1379,12 @@ void gracefully_kill_them_all(int signum) {
                 }
         }
 
+
```
Comment (xrmx) [inline core/uwsgi.c:1382]:
```suggestion
```

File: core/uwsgi.c [hunk 3]
```diff
@@ -1377,6 +1379,12 @@ void gracefully_kill_them_all(int signum) {
...
+        for (i = 1; i <= uwsgi.numproc; i++) {
+            if (uwsgi.workers[i].pid > 0) {
+                waitpid(uwsgi.workers[i].pid, &waitpid_status, 0);
+            }
+        }
```
Comment (xrmx) [inline core/uwsgi.c:1387]:
```suggestion
        }

```

**Comment by xrmx** [comment]
Thanks a lot!

**Comment by karolyi** [comment]
Thank you very much for this! This change has fixed my spoolers not being killed (staying in defunct state), while trying to do a touch-reload. It resulted in my entire uwsgi stack hanging on reload.
